### ISSUE TITLE
Rasp Road seg., The road must be perfect otherwise runtime err

### ISSUE THREAD

**Issue by ghost** [utkuucak/Utku-Sinan-Undergrad-Thesis#15]
As mentioned #7 the program gives runtime error if it doesnt recognize a line at any time. This is a challenging issue for real time road segmentation.  The road papers should be perfect or functions needs exception handling.

**Comment by ghost** [comment]
The modified program main2deneme.py gives error for functions.py
`Traceback (most recent call last):
  File "main2deneme.py", line 7, in <module>
    from functions import Functions
  File "/home/pi/Desktop/Abschlussprojekt/main/functions.py", line 77
    cv2.line(line_image, *line,  color, thickness)
SyntaxError: only named arguments may follow *expression
`
